# Generated by Django 5.0.7 on 2026-06-13 07:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamas', '0001_initial'),
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CHAMA_CREATED', 'Chama created'), ('CHAMA_JOINED', 'Joined chama'), ('CHAMA_LEFT', 'Left chama'), ('CONTRIBUTION_MADE', 'Contribution made'), ('CONTRIBUTION_VERIFIED', 'Contribution verified'), ('LOAN_APPLIED', 'Loan applied'), ('LOAN_APPROVED', 'Loan approved'), ('LOAN_DISBURSED', 'Loan disbursed'), ('LOAN_REPAID', 'Loan repaid'), ('MEETING_SCHEDULED', 'Meeting scheduled'), ('ATTENDANCE_RECORDED', 'Attendance recorded'), ('LIQUIDITY_REQUESTED', 'Liquidity requested'), ('INTEREST_EXPRESSED', 'Interest expressed'), ('OFFER_MADE', 'Offer made'), ('OFFER_ACCEPTED', 'Offer accepted'), ('OFFER_DECLINED', 'Offer declined'), ('OFFER_COUNTERED', 'Offer countered'), ('SETTLEMENT_INITIATED', 'Settlement initiated'), ('SETTLEMENT_COMPLETED', 'Settlement completed'), ('SETTLEMENT_DISPUTED', 'Settlement disputed'), ('SETTLEMENT_RESOLVED', 'Settlement resolved'), ('ACCOUNT_REGISTERED', 'Account registered'), ('PROFILE_UPDATED', 'Profile updated'), ('VERIFICATION_COMPLETED', 'Verification completed'), ('TWO_FACTOR_ENABLED', '2FA enabled'), ('TWO_FACTOR_DISABLED', '2FA disabled'), ('PASSWORD_CHANGED', 'Password changed')], db_index=True, help_text='Type of activity.', max_length=30)),
                ('title', models.CharField(help_text='Human-readable activity title.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed activity description.')),
                ('reference_id', models.UUIDField(blank=True, help_text='UUID of the related object (contribution, loan, settlement, etc.).', null=True)),
                ('reference_type', models.CharField(blank=True, default='', help_text='Type of the related object (Contribution, Loan, etc.).', max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Additional contextual data (amounts, names, etc.).')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='When the activity occurred.')),
                ('chama', models.ForeignKey(blank=True, help_text='Related chama if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='chamas.chama')),
                ('sacco', models.ForeignKey(blank=True, help_text='Related SACCO if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='investments.sacco')),
                ('user', models.ForeignKey(help_text='User who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_ac_user_id_9aae35_idx'), models.Index(fields=['activity_type', '-created_at'], name='activity_ac_activit_d903ad_idx'), models.Index(fields=['chama', '-created_at'], name='activity_ac_chama_i_603f52_idx')],
            },
        ),
    ]
