# Generated by Django 5.0.7 on 2026-05-29 16:01

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidityRequest',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('share_quantity', models.DecimalField(decimal_places=4, help_text='Number of shares offered.', max_digits=20, validators=[apps.core.validators.validate_share_quantity])),
                ('expected_price_per_share', models.DecimalField(blank=True, decimal_places=2, help_text="Seller's expected price per share (optional).", max_digits=15, null=True)),
                ('minimum_price_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum acceptable price per share (optional).', max_digits=15, null=True)),
                ('total_expected_value', models.DecimalField(blank=True, decimal_places=2, help_text='Total expected value for the shares.', max_digits=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active - Seeking Buyers'), ('MATCHED', 'Matched - Buyer Found'), ('IN_NEGOTIATION', 'In Negotiation'), ('ACCEPTED', 'Offer Accepted'), ('SETTLED', 'Settled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', help_text='Current status of the request.', max_length=30)),
                ('urgency', models.CharField(choices=[('STANDARD', 'Standard - Within 1 Week'), ('PRIORITY', 'Priority - Within 48 Hours'), ('URGENT', 'Urgent - Within 24 Hours')], default='STANDARD', help_text='How quickly the seller needs funds.', max_length=20)),
                ('allow_institutional_buyers', models.BooleanField(default=True, help_text='Whether institutional buyers can express interest.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this request expires if not matched.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes from the seller.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(help_text='The member seeking liquidity.', on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidity Request',
                'verbose_name_plural': 'Liquidity Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('status', models.CharField(choices=[('PENDING_SELLER_REVIEW', 'Pending Seller Review'), ('CONNECTED', 'Connected - In Discussion'), ('OFFER_MADE', 'Offer Made'), ('OFFER_COUNTERED', 'Offer Countered'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_DECLINED', 'Offer Declined'), ('SETTLEMENT_INITIATED', 'Settlement Initiated'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed')], db_index=True, default='PENDING_SELLER_REVIEW', help_text='Current connection status.', max_length=30)),
                ('agreed_price_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed price per share (if accepted).', max_digits=15, null=True)),
                ('agreed_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Agreed share quantity (if accepted).', max_digits=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total transaction amount.', max_digits=20, null=True)),
                ('settlement_intent_id', models.UUIDField(blank=True, help_text='Reference to the settlement intent when initiated.', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the offer was accepted.', null=True)),
                ('settled_at', models.DateTimeField(blank=True, help_text='When settlement completed.', null=True)),
                ('buyer', models.ForeignKey(help_text='The buyer in this connection.', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_connections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(help_text='The seller in this connection.', on_delete=django.db.models.deletion.CASCADE, related_name='seller_connections', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('liquidity_request', models.ForeignKey(help_text='The liquidity request.', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='investments.liquidityrequest')),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerInterest',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this interest is still active.')),
                ('buyer_message', models.TextField(blank=True, default='', help_text='Optional message from the buyer to the seller.')),
                ('viewed_by_seller', models.BooleanField(default=False, help_text='Whether the seller has viewed this interest.')),
                ('buyer', models.ForeignKey(help_text='The potential buyer.', on_delete=django.db.models.deletion.CASCADE, related_name='expressed_interests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('liquidity_request', models.ForeignKey(help_text='The liquidity request the buyer is interested in.', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_interests', to='investments.liquidityrequest')),
            ],
            options={
                'verbose_name': 'Buyer Interest',
                'verbose_name_plural': 'Buyer Interests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_share', models.DecimalField(decimal_places=2, help_text='Offered price per share.', max_digits=15, validators=[apps.core.validators.validate_positive_amount])),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity of shares in this offer.', max_digits=20, validators=[apps.core.validators.validate_share_quantity])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total offer amount.', max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COUNTERED', 'Countered'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Current offer status.', max_length=20)),
                ('message', models.TextField(blank=True, default='', help_text='Optional message accompanying the offer.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When the offer was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the offer was last modified.')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the offer was responded to.', null=True)),
                ('connection', models.ForeignKey(help_text='The connection this offer belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='investments.connection')),
                ('offered_by', models.ForeignKey(help_text='The user who made this offer.', on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SACCO',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('name', models.CharField(db_index=True, help_text='Official name of the SACCO.', max_length=255)),
                ('registration_number', models.CharField(help_text='SASRA registration number.', max_length=50, unique=True)),
                ('sasra_tier', models.CharField(choices=[('TIER_1', 'Tier 1 - Large SACCOs'), ('TIER_2', 'Tier 2 - Medium SACCOs'), ('TIER_3', 'Tier 3 - Small SACCOs'), ('UNRATED', 'Unrated')], default='UNRATED', help_text='SASRA regulatory tier classification.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('UNDER_REVIEW', 'Under Review'), ('HALTED', 'Trading Halted')], db_index=True, default='UNDER_REVIEW', help_text='Current operational status on the platform.', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the SACCO and its services.')),
                ('website', models.URLField(blank=True, default='', help_text='SACCO website URL.')),
                ('logo', models.ImageField(blank=True, help_text='SACCO logo image.', null=True, upload_to='sacco_logos/%Y/%m/')),
                ('total_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total assets under management.', max_digits=20)),
                ('total_members', models.PositiveIntegerField(default=0, help_text='Total number of registered members.')),
                ('total_shares_outstanding', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total shares issued by the SACCO.', max_digits=20)),
                ('dividend_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Most recent annual dividend rate (percentage).', max_digits=6, validators=[apps.core.validators.validate_percentage])),
                ('dividend_year', models.PositiveIntegerField(blank=True, help_text='Year of the most recent dividend declaration.', null=True)),
                ('last_disclosure_date', models.DateField(blank=True, help_text='Date of the last financial disclosure submission.', null=True)),
                ('disclosure_due_date', models.DateField(blank=True, help_text='Date when the next financial disclosure is due.', null=True)),
                ('trading_halted', models.BooleanField(default=False, help_text='Whether trading is currently halted for this SACCO.')),
                ('halt_reason', models.TextField(blank=True, default='', help_text='Reason for trading halt if applicable.')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the SACCO was verified.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Platform admin who verified this SACCO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_saccos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SACCO',
                'verbose_name_plural': 'SACCOs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='liquidityrequest',
            name='sacco',
            field=models.ForeignKey(help_text='The SACCO whose shares are being offered.', on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_requests', to='investments.sacco'),
        ),
        migrations.CreateModel(
            name='SACCOMemberHolding',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('total_shares', models.DecimalField(decimal_places=4, help_text='Total shares owned.', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('reserved_shares', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Shares reserved for pending transactions.', max_digits=20)),
                ('member_since', models.DateField(blank=True, help_text='Date when the member joined this SACCO.', null=True)),
                ('member_number', models.CharField(blank=True, default='', help_text="Member's registration number with the SACCO.", max_length=50)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='When holdings were last verified with the SACCO.', null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('MISMATCH', 'Mismatch Detected')], default='PENDING', help_text='Verification status with the SACCO.', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(help_text='The SACCO where shares are held.', on_delete=django.db.models.deletion.CASCADE, related_name='member_holdings', to='investments.sacco')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The platform user who holds these shares.', on_delete=django.db.models.deletion.CASCADE, related_name='sacco_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SACCO Member Holding',
                'verbose_name_plural': 'SACCO Member Holdings',
            },
        ),
        migrations.AddField(
            model_name='liquidityrequest',
            name='holding',
            field=models.ForeignKey(help_text='The specific holding being sold from.', on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_requests', to='investments.saccomemberholding'),
        ),
        migrations.CreateModel(
            name='SACCOShareClass',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('share_class', models.CharField(choices=[('NON_WITHDRAWABLE', 'Non-Withdrawable Deposit'), ('WITHDRAWABLE', 'Withdrawable Deposit'), ('DEVELOPMENT', 'Development Shares'), ('SPECIAL', 'Special Class Shares')], default='NON_WITHDRAWABLE', help_text='Type of share class.', max_length=30)),
                ('nominal_value', models.DecimalField(decimal_places=2, help_text='Nominal value per share.', max_digits=15, validators=[apps.core.validators.validate_positive_amount])),
                ('total_issued', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total shares issued in this class.', max_digits=20)),
                ('minimum_holding', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Minimum shares a member must hold.', max_digits=15)),
                ('is_transferable', models.BooleanField(default=True, help_text='Whether shares in this class can be transferred.')),
                ('lock_in_period_months', models.PositiveIntegerField(default=0, help_text='Lock-in period before shares can be sold.')),
                ('dividend_eligible', models.BooleanField(default=True, help_text='Whether these shares earn dividends.')),
                ('voting_rights', models.BooleanField(default=True, help_text='Whether these shares carry voting rights.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(help_text='The SACCO these shares belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='share_classes', to='investments.sacco')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SACCO Share Class',
                'verbose_name_plural': 'SACCO Share Classes',
            },
        ),
        migrations.AddField(
            model_name='saccomemberholding',
            name='share_class',
            field=models.ForeignKey(help_text='The share class held.', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investments.saccoshareclass'),
        ),
        migrations.AddField(
            model_name='liquidityrequest',
            name='share_class',
            field=models.ForeignKey(help_text='The share class being offered.', on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_requests', to='investments.saccoshareclass'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['seller', 'status'], name='investments_seller__d3b5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['buyer', 'status'], name='investments_buyer_i_054b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['status'], name='investments_status_ebc8ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buyerinterest',
            unique_together={('liquidity_request', 'buyer')},
        ),
        migrations.AddIndex(
            model_name='sacco',
            index=models.Index(fields=['name'], name='investments_name_ca33b0_idx'),
        ),
        migrations.AddIndex(
            model_name='sacco',
            index=models.Index(fields=['registration_number'], name='investments_registr_79ed32_idx'),
        ),
        migrations.AddIndex(
            model_name='sacco',
            index=models.Index(fields=['sasra_tier'], name='investments_sasra_t_469ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='sacco',
            index=models.Index(fields=['status'], name='investments_status_ad1401_idx'),
        ),
        migrations.AddIndex(
            model_name='sacco',
            index=models.Index(fields=['trading_halted'], name='investments_trading_8cc961_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saccoshareclass',
            unique_together={('sacco', 'share_class')},
        ),
        migrations.AddIndex(
            model_name='saccomemberholding',
            index=models.Index(fields=['user', 'sacco'], name='investments_user_id_3a96fd_idx'),
        ),
        migrations.AddIndex(
            model_name='saccomemberholding',
            index=models.Index(fields=['verification_status'], name='investments_verific_6cb166_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saccomemberholding',
            unique_together={('user', 'sacco', 'share_class')},
        ),
        migrations.AddIndex(
            model_name='liquidityrequest',
            index=models.Index(fields=['seller', 'status'], name='investments_seller__a91f37_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityrequest',
            index=models.Index(fields=['sacco', 'status'], name='investments_sacco_i_db2da3_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityrequest',
            index=models.Index(fields=['status'], name='investments_status_e9b032_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityrequest',
            index=models.Index(fields=['urgency'], name='investments_urgency_1d33b5_idx'),
        ),
    ]
