# Generated by Django 5.0.7 on 2026-06-13 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['liquidity_request', 'status'], name='investments_liquidi_2c4a91_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidityrequest',
            index=models.Index(fields=['sacco', 'status', 'urgency'], name='investments_sacco_i_c464f5_idx'),
        ),
    ]
