# Generated by Django 5.0.7 on 2026-06-13 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamas', '0004_loan_early_repayment_discount_loan_is_restructured_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=300, help_text='Credit score (300-850).')),
                ('grade', models.CharField(blank=True, default='', help_text='Letter grade (A+, A, B, C, D, E).', max_length=3)),
                ('contribution_score', models.PositiveIntegerField(default=0)),
                ('repayment_score', models.PositiveIntegerField(default=0)),
                ('attendance_score', models.PositiveIntegerField(default=0)),
                ('savings_score', models.PositiveIntegerField(default=0)),
                ('trust_score', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_scores', to='chamas.chama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Score',
                'verbose_name_plural': 'Credit Scores',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['user', 'chama', '-calculated_at'], name='scoring_cre_user_id_127cef_idx')],
            },
        ),
    ]
