# Generated by Django 5.0.7 on 2026-06-16 18:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0006_chama_constitution_chama_constitution_uploaded_at_and_more'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanUnderwriting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_score_value', models.PositiveIntegerField(default=0)),
                ('chama_health_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('APPROVE_WITH_CONDITIONS', 'Approve with Conditions'), ('FLAG_FOR_REVIEW', 'Flag for Manual Review'), ('REJECT', 'Reject')], default='FLAG_FOR_REVIEW', max_length=30)),
                ('confidence_score', models.PositiveIntegerField(default=50, help_text='Confidence in the automated decision (0-100).')),
                ('reasoning', models.JSONField(default=list, help_text='List of factors contributing to the decision.')),
                ('conditions', models.JSONField(default=list, help_text='Conditions for approval if APPROVE_WITH_CONDITIONS.')),
                ('overridden_decision', models.CharField(blank=True, choices=[('APPROVE', 'Approve'), ('APPROVE_WITH_CONDITIONS', 'Approve with Conditions'), ('FLAG_FOR_REVIEW', 'Flag for Manual Review'), ('REJECT', 'Reject')], max_length=30, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.creditscore')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='underwriting', to='chamas.loan')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_underwritings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Underwriting',
                'verbose_name_plural': 'Loan Underwritings',
                'ordering': ['-created_at'],
            },
        ),
    ]
