version: '3.8'

services:
  app:
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_roles &&
             python manage.py create_notification_templates &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True

  celery_worker:
    command: celery -A sacco_bridge worker -l debug -Q celery,settlements,analytics,maintenance,notifications,payments

  celery_beat:
    command: celery -A sacco_bridge beat -l debug