# Generated by Django 5.0.7 on 2026-06-12 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('document_type', models.CharField(choices=[('TERMS', 'Terms & Conditions'), ('PRIVACY', 'Privacy Policy')], help_text='Type of legal document.', max_length=20)),
                ('title', models.CharField(help_text="Document title (e.g., 'Terms & Conditions v2.1').", max_length=255)),
                ('version', models.CharField(help_text="Semantic version (e.g., '2.1.0').", max_length=20)),
                ('content', models.TextField(help_text='Full document content in markdown or HTML.')),
                ('summary', models.TextField(blank=True, default='', help_text='Plain-language summary of key changes.')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Whether this is the currently active version.')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this version was published.', null=True)),
                ('effective_from', models.DateTimeField(blank=True, help_text='When this version takes effect.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, help_text='Admin who published this version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_legal_docs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='UserLegalAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='When the user accepted.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at time of acceptance.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser/device info at time of acceptance.')),
                ('document', models.ForeignKey(help_text='The document version that was accepted.', on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='legal.legaldocument')),
                ('user', models.ForeignKey(help_text='The user who accepted.', on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Legal Acceptance',
                'verbose_name_plural': 'User Legal Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['document_type', 'is_current'], name='legal_legal_documen_b52cea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together={('document_type', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='userlegalacceptance',
            unique_together={('user', 'document')},
        ),
    ]
