# Generated by Django 5.0.7 on 2026-06-13 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('LOAN_AGREEMENT', 'Loan Agreement'), ('SHARE_TRANSFER', 'Share Transfer Form'), ('TERMS_ACCEPTANCE', 'Terms & Conditions'), ('PRIVACY_ACCEPTANCE', 'Privacy Policy'), ('CHAMA_CONSTITUTION', 'Chama Constitution')], max_length=30)),
                ('document_reference', models.CharField(help_text='Reference to the signed document (e.g., loan ID).', max_length=255)),
                ('document_title', models.CharField(max_length=255)),
                ('verification_method', models.CharField(choices=[('SMS_OTP', 'SMS OTP'), ('EMAIL_OTP', 'Email OTP'), ('TOTP', '2FA Code')], default='SMS_OTP', max_length=20)),
                ('verification_code', models.CharField(blank=True, default='', help_text='OTP sent for verification (cleared after signing).', max_length=6)),
                ('verification_expiry', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('certificate_hash', models.CharField(blank=True, default='', help_text='SHA256 hash of the signature certificate.', max_length=64)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['-created_at'],
                'unique_together': {('signer', 'document_type', 'document_reference')},
            },
        ),
    ]
