# Generated by Django 5.0.7 on 2026-06-16 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_trusted', models.BooleanField(default=False)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='TransactionRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('SETTLEMENT', 'Settlement'), ('LOAN', 'Loan'), ('CONTRIBUTION', 'Contribution'), ('WITHDRAWAL', 'Withdrawal')], max_length=30)),
                ('transaction_reference', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_score', models.PositiveIntegerField(default=0, help_text='Risk score 0-100 (higher = more risky)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=10)),
                ('recommended_action', models.CharField(choices=[('ALLOW', 'Allow'), ('FLAG', 'Flag for Review'), ('HOLD', 'Hold Funds'), ('BLOCK', 'Block Transaction')], default='ALLOW', max_length=10)),
                ('applied_action', models.CharField(blank=True, choices=[('ALLOW', 'Allow'), ('FLAG', 'Flag for Review'), ('HOLD', 'Hold Funds'), ('BLOCK', 'Block Transaction')], max_length=10, null=True)),
                ('triggers', models.JSONField(default=list, help_text='List of fraud signals that were triggered.')),
                ('velocity_24h_count', models.PositiveIntegerField(default=0)),
                ('velocity_24h_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('velocity_7d_count', models.PositiveIntegerField(default=0)),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_reputation_score', models.PositiveIntegerField(default=50)),
                ('location_mismatch', models.BooleanField(default=False)),
                ('is_new_device', models.BooleanField(default=False)),
                ('is_unusual_hour', models.BooleanField(default=False)),
                ('is_unusual_amount', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Risk Assessment',
                'verbose_name_plural': 'Transaction Risk Assessments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='fraud_trans_user_id_e545cc_idx'), models.Index(fields=['risk_level', '-created_at'], name='fraud_trans_risk_le_faaf35_idx'), models.Index(fields=['applied_action'], name='fraud_trans_applied_4024b5_idx')],
            },
        ),
    ]
