# Generated by Django 5.0.7 on 2026-06-13 12:41

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount held in escrow.', max_digits=15)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform fee to be deducted.', max_digits=15)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('FUNDED', 'Funded - Buyer Paid'), ('RELEASED', 'Released - Seller Paid'), ('REFUNDED', 'Refunded - Returned to Buyer'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20)),
                ('buyer_ref', models.CharField(blank=True, default='', help_text='External reference for buyer payment.', max_length=128)),
                ('seller_ref', models.CharField(blank=True, default='', help_text='External reference for seller payout.', max_length=128)),
                ('refund_ref', models.CharField(blank=True, default='', help_text='External reference for refund if applicable.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_payments', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_receipts', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.OneToOneField(help_text='The settlement this escrow secures.', on_delete=django.db.models.deletion.PROTECT, related_name='escrow', to='transactions.settlementintent')),
            ],
            options={
                'verbose_name': 'Escrow Account',
                'verbose_name_plural': 'Escrow Accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='escrow_escr_status_0c88f9_idx'), models.Index(fields=['buyer', 'status'], name='escrow_escr_buyer_i_0d34dc_idx'), models.Index(fields=['seller', 'status'], name='escrow_escr_seller__2ae451_idx')],
            },
        ),
    ]
