# Generated by Django 5.0.7 on 2026-06-16 18:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowaccount',
            name='hold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount held (may be partial).', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the hold automatically expires.', null=True),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='hold_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='hold_triggered_by',
            field=models.CharField(blank=True, choices=[('FRAUD_DETECTION', 'Fraud Detection'), ('LARGE_AMOUNT', 'Large Transaction'), ('FIRST_TRANSACTION', 'First Transaction'), ('NEW_DEVICE', 'New Device'), ('ADMIN_MANUAL', 'Admin Manual Hold')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='released_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount progressively released.', max_digits=15),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_escrows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escrowaccount',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('FUNDED', 'Funded - Buyer Paid'), ('HELD', 'Held - Under Review'), ('HELD_PARTIAL', 'Partially Held'), ('RELEASED', 'Released - Seller Paid'), ('REFUNDED', 'Refunded - Returned to Buyer'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=20),
        ),
    ]
