# Generated by Django 5.0.7 on 2026-07-07 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARN', 'Warn'), ('ERROR', 'Error')], db_index=True, default='ERROR', max_length=10)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('stack', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Error Log',
                'verbose_name_plural': 'Client Error Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
