# Generated by Django 5.0.7 on 2026-07-07 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_clienterrorlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VERIFY_SACCO', 'Verify SACCO'), ('SUSPEND_SACCO', 'Suspend SACCO'), ('REACTIVATE_SACCO', 'Reactivate SACCO'), ('RESOLVE_DISPUTE', 'Resolve Dispute'), ('APPROVE_DELETION', 'Approve Deletion'), ('BULK_USER_ACTION', 'Bulk User Action'), ('BULK_CHAMA_ACTION', 'Bulk Chama Action')], db_index=True, max_length=30)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, default='', help_text='Human-readable description of the target.', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional data needed to execute the action.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_reviews', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Admin Approval',
                'verbose_name_plural': 'Admin Approvals',
                'ordering': ['-created_at'],
            },
        ),
    ]
