# Generated by Django 5.0.7 on 2026-05-29 16:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('session_type', models.CharField(choices=[('GENERAL_SUPPORT', 'General Support'), ('CHAMA_SETUP', 'Chama Setup Help'), ('CHAMA_MANAGEMENT', 'Chama Management'), ('INVESTMENT_GUIDANCE', 'Investment Guidance'), ('SETTLEMENT_HELP', 'Settlement Help'), ('DISPUTE_ASSISTANCE', 'Dispute Assistance'), ('ONBOARDING', 'Onboarding Help')], default='GENERAL_SUPPORT', help_text='Type of support session.', max_length=30)),
                ('title', models.CharField(blank=True, default='', help_text='Auto-generated or user-provided session title.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the session is still active.')),
                ('context_data', models.JSONField(default=dict, help_text='Additional context for the AI (user profile, platform data).')),
                ('total_tokens_used', models.PositiveIntegerField(default=0, help_text='Total tokens consumed in this session.')),
                ('resolved', models.BooleanField(default=False, help_text="Whether the user's issue was resolved.")),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='User feedback rating for the session.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user in this conversation.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], help_text='Who sent this message.', max_length=20)),
                ('content', models.TextField(help_text='Message content.')),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Tokens consumed for this message.')),
                ('ai_model', models.CharField(blank=True, default='', help_text='AI model used to generate this response.', max_length=50)),
                ('intent_detected', models.CharField(blank=True, default='', help_text='Intent classified by the AI.', max_length=100)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score for intent classification.', null=True)),
                ('action_type', models.CharField(blank=True, default='', help_text='Action triggered by this message (if any).', max_length=50)),
                ('action_data', models.JSONField(default=dict, help_text='Data for the triggered action.')),
                ('sources', models.JSONField(default=list, help_text='Knowledge base sources used for the response.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The session this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('title', models.CharField(help_text='Article title.', max_length=255)),
                ('content', models.TextField(help_text='Article content in markdown format.')),
                ('category', models.CharField(choices=[('CHAMA_BASICS', 'Chama Basics'), ('CHAMA_SETUP', 'Chama Setup'), ('CONTRIBUTIONS', 'Contributions'), ('LOANS', 'Loans'), ('MEETINGS', 'Meetings'), ('SACCO_SHARES', 'SACCO Shares'), ('BUYING_SHARES', 'Buying Shares'), ('SELLING_SHARES', 'Selling Shares'), ('SETTLEMENTS', 'Settlements'), ('DISPUTES', 'Disputes'), ('ACCOUNT_SECURITY', 'Account Security'), ('FEES_PRICING', 'Fees & Pricing'), ('PLATFORM_BASICS', 'Platform Basics'), ('REGULATIONS', 'Regulations & Compliance')], help_text='Knowledge category.', max_length=30)),
                ('tags', models.JSONField(default=list, help_text='Search tags for retrieval.')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether this article is published and usable by the AI.')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Priority for retrieval (higher = more important).')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this article was used in responses.')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this article was last used in a response.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the article was last reviewed.', null=True)),
                ('authored_by', models.ForeignKey(blank=True, help_text='Who wrote this article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Who reviewed this article.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Article',
                'verbose_name_plural': 'Knowledge Articles',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='chatbot_cha_user_id_9fd70b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_type'], name='chatbot_cha_session_b0367e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_24e989_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['category', 'is_published'], name='chatbot_kno_categor_5c1cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['is_published'], name='chatbot_kno_is_publ_a7a68c_idx'),
        ),
    ]
