# Generated by Django 5.0.7 on 2026-06-02 09:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamas', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('receipt_number', models.CharField(db_index=True, help_text='Unique receipt number (format: RCP-YYYYMMDD-XXXXXX).', max_length=50, unique=True)),
                ('receipt_type', models.CharField(choices=[('SETTLEMENT_BUY', 'Share Purchase'), ('SETTLEMENT_SELL', 'Share Sale'), ('CHAMA_CONTRIBUTION', 'Chama Contribution'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('PLATFORM_FEE', 'Platform Fee')], help_text='Type of receipt.', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in KSh.', max_digits=15)),
                ('description', models.CharField(help_text='Human-readable description of the transaction.', max_length=500)),
                ('party_name', models.CharField(help_text='Name of the other party (buyer/seller/chama).', max_length=255)),
                ('verification_code', models.CharField(help_text='Unique verification code encoded in QR.', max_length=64, unique=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF receipt file.', null=True, upload_to='receipts/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When the receipt was generated.')),
                ('contribution', models.ForeignKey(blank=True, help_text='Related contribution if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='chamas.contribution')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('loan_repayment', models.ForeignKey(blank=True, help_text='Related loan repayment if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='chamas.loanrepayment')),
                ('settlement', models.ForeignKey(blank=True, help_text='Related settlement if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='transactions.settlementintent')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user this receipt belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'receipt_type'], name='receipts_re_user_id_b87d02_idx'), models.Index(fields=['receipt_number'], name='receipts_re_receipt_840679_idx'), models.Index(fields=['generated_at'], name='receipts_re_generat_f15894_idx')],
            },
        ),
    ]
