# Generated by Django 5.0.7 on 2026-06-02 09:32

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementIntent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public-facing unique identifier for this settlement.', unique=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Idempotency key to prevent duplicate processing.', max_length=128, unique=True)),
                ('state', models.CharField(choices=[('MATCH_PROPOSED', 'Match Proposed'), ('INTENT_LOCKED', 'Intent Locked'), ('BUYER_DEBIT_INITIATED', 'Buyer Debit Initiated'), ('BUYER_DEBIT_CONFIRMED', 'Buyer Debit Confirmed'), ('SELLER_CREDIT_INITIATED', 'Seller Credit Initiated'), ('SELLER_CREDIT_CONFIRMED', 'Seller Credit Confirmed'), ('LEDGER_FINALIZED', 'Ledger Finalized'), ('COMPENSATING', 'Compensating - Rolling Back'), ('REVERSED', 'Reversed - Rolled Back'), ('DISPUTED_MANUAL', 'Disputed - Manual Review'), ('CLOSED_BY_TRUSTEE', 'Closed by Trustee')], db_index=True, default='MATCH_PROPOSED', help_text='Current state in the settlement state machine.', max_length=30)),
                ('version', models.PositiveIntegerField(default=0, help_text='Optimistic locking version counter.')),
                ('buyer_sacco_id', models.IntegerField(help_text="ID of the buyer's SACCO.")),
                ('buyer_sacco_name', models.CharField(help_text="Name of the buyer's SACCO for audit trail.", max_length=255)),
                ('seller_sacco_id', models.IntegerField(help_text="ID of the seller's SACCO.")),
                ('seller_sacco_name', models.CharField(help_text="Name of the seller's SACCO for audit trail.", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in KSh.', max_digits=15, validators=[apps.core.validators.validate_positive_amount])),
                ('share_quantity', models.DecimalField(decimal_places=4, help_text='Number of shares being transferred.', max_digits=20, validators=[apps.core.validators.validate_share_quantity])),
                ('price_per_share', models.DecimalField(decimal_places=2, help_text='Agreed price per share.', max_digits=15, validators=[apps.core.validators.validate_positive_amount])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform fee for this settlement.', max_digits=15)),
                ('net_seller_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net amount the seller receives after fees.', max_digits=15)),
                ('buyer_debit_ref', models.CharField(blank=True, default='', help_text="Transaction reference from buyer's SACCO for the debit.", max_length=128)),
                ('seller_credit_ref', models.CharField(blank=True, default='', help_text="Transaction reference from seller's SACCO for the credit.", max_length=128)),
                ('buyer_reversal_ref', models.CharField(blank=True, default='', help_text='Reference for buyer debit reversal if applicable.', max_length=128)),
                ('liquidity_request_id', models.UUIDField(blank=True, help_text='Reference to the original liquidity request.', null=True)),
                ('matched_at', models.DateTimeField(blank=True, help_text='When the match was first proposed.', null=True)),
                ('locked_at', models.DateTimeField(blank=True, help_text='When the intent was locked and funds reserved.', null=True)),
                ('buyer_debited_at', models.DateTimeField(blank=True, help_text='When buyer funds were successfully debited.', null=True)),
                ('seller_credited_at', models.DateTimeField(blank=True, help_text='When seller was successfully credited.', null=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='When the ledger was finalized.', null=True)),
                ('reversed_at', models.DateTimeField(blank=True, help_text='When the transaction was reversed.', null=True)),
                ('ttl_seconds', models.PositiveIntegerField(default=300, help_text='Time-to-live in seconds before auto-expiry.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this intent expires if not progressed.', null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of recovery attempts made.')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum number of automated recovery attempts.')),
                ('dispute_opened_at', models.DateTimeField(blank=True, help_text='When a dispute was opened for this settlement.', null=True)),
                ('dispute_resolved_at', models.DateTimeField(blank=True, help_text='When the dispute was resolved.', null=True)),
                ('dispute_resolution_type', models.CharField(blank=True, choices=[('MANUAL_CREDIT_CONFIRMED', 'Manual Credit Confirmed by SACCO'), ('BUYER_REVERSAL_INITIATED', 'Buyer Reversal Initiated'), ('ESCALATED_TO_TRUSTEE', 'Escalated to Trustee'), ('FORCE_MARKED_SETTLED', 'Force Marked Settled'), ('MANUAL_REVERSAL', 'Manual Reversal')], help_text='How the dispute was resolved.', max_length=40, null=True)),
                ('trustee_case_number', models.CharField(blank=True, default='', help_text='Trustee bank case reference if escalated.', max_length=100)),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Internal notes for operations team (not visible to members).')),
                ('buyer', models.ForeignKey(help_text='The buyer in this settlement.', on_delete=django.db.models.deletion.PROTECT, related_name='buyer_settlements', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(blank=True, help_text='The connection that led to this settlement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='investments.connection')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('dispute_resolved_by', models.ForeignKey(blank=True, help_text='The staff member who resolved the dispute.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(help_text='The seller in this settlement.', on_delete=django.db.models.deletion.PROTECT, related_name='seller_settlements', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Settlement Intent',
                'verbose_name_plural': 'Settlement Intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('MATCH_PROPOSED', 'Match Proposed'), ('INTENT_LOCKED', 'Intent Locked'), ('BUYER_DEBIT_INITIATED', 'Buyer Debit Initiated'), ('BUYER_DEBIT_CONFIRMED', 'Buyer Debit Confirmed'), ('SELLER_CREDIT_INITIATED', 'Seller Credit Initiated'), ('SELLER_CREDIT_CONFIRMED', 'Seller Credit Confirmed'), ('LEDGER_FINALIZED', 'Ledger Finalized'), ('COMPENSATING', 'Compensating - Rolling Back'), ('REVERSED', 'Reversed - Rolled Back'), ('DISPUTED_MANUAL', 'Disputed - Manual Review'), ('CLOSED_BY_TRUSTEE', 'Closed by Trustee')], help_text='Previous state before this transition.', max_length=30)),
                ('to_state', models.CharField(choices=[('MATCH_PROPOSED', 'Match Proposed'), ('INTENT_LOCKED', 'Intent Locked'), ('BUYER_DEBIT_INITIATED', 'Buyer Debit Initiated'), ('BUYER_DEBIT_CONFIRMED', 'Buyer Debit Confirmed'), ('SELLER_CREDIT_INITIATED', 'Seller Credit Initiated'), ('SELLER_CREDIT_CONFIRMED', 'Seller Credit Confirmed'), ('LEDGER_FINALIZED', 'Ledger Finalized'), ('COMPENSATING', 'Compensating - Rolling Back'), ('REVERSED', 'Reversed - Rolled Back'), ('DISPUTED_MANUAL', 'Disputed - Manual Review'), ('CLOSED_BY_TRUSTEE', 'Closed by Trustee')], help_text='New state after this transition.', max_length=30)),
                ('trigger', models.CharField(choices=[('SYSTEM_MATCH', 'System Match'), ('INTENT_CREATED', 'Intent Created'), ('BUYER_SACCO_SUCCESS', 'Buyer SACCO Success'), ('BUYER_SACCO_FAILURE', 'Buyer SACCO Failure'), ('SELLER_SACCO_SUCCESS', 'Seller SACCO Success'), ('SELLER_SACCO_FAILURE', 'Seller SACCO Failure'), ('API_TIMEOUT', 'API Timeout'), ('API_RETRY_EXHAUSTED', 'API Retry Exhausted'), ('STATUS_LOOKUP', 'Status Lookup'), ('AMBIGUOUS_RESULT', 'Ambiguous Result'), ('RECOVERY_WORKER', 'Recovery Worker'), ('OPS_MANUAL_CONFIRMATION', 'Ops Manual Confirmation'), ('OPS_REVERSAL_INITIATED', 'Ops Reversal Initiated'), ('OPS_ESCALATED_TO_TRUSTEE', 'Ops Escalated to Trustee'), ('OPS_FORCE_SETTLED', 'Ops Force Settled'), ('OPS_NOTE_ADDED', 'Ops Note Added'), ('TRUSTEE_RESOLUTION', 'Trustee Resolution'), ('TTL_EXPIRED', 'TTL Expired'), ('COMPENSATION_SUCCESS', 'Compensation Success'), ('COMPENSATION_FAILURE', 'Compensation Failure')], help_text='What triggered this state transition.', max_length=50)),
                ('external_ref', models.CharField(blank=True, default='', help_text='External reference (e.g., SACCO transaction ID).', max_length=128)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context data for this event.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this event occurred.')),
                ('actor', models.CharField(default='system', help_text='Who or what caused this event (system, worker instance, user).', max_length=100)),
                ('intent', models.ForeignKey(help_text='The settlement intent this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transactions.settlementintent')),
            ],
            options={
                'verbose_name': 'Settlement Event',
                'verbose_name_plural': 'Settlement Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_id', models.IntegerField(help_text='SACCO where shares are held.')),
                ('share_quantity', models.DecimalField(decimal_places=4, help_text='Number of shares transferred.', max_digits=20)),
                ('price_per_share', models.DecimalField(decimal_places=2, help_text='Price per share at settlement.', max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total transaction value.', max_digits=15)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform fee charged.', max_digits=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this ledger entry was created.')),
                ('is_reversed', models.BooleanField(default=False, help_text='Whether this ledger entry has been reversed.')),
                ('buyer', models.ForeignKey(help_text='The buyer receiving shares.', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_purchases', to=settings.AUTH_USER_MODEL)),
                ('reversal_entry', models.OneToOneField(blank=True, help_text='Reference to the reversal ledger entry if reversed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_entry', to='transactions.ledgerentry')),
                ('seller', models.ForeignKey(help_text='The seller transferring shares.', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_sales', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.OneToOneField(help_text='The settlement that created this ledger entry.', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='transactions.settlementintent')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_type', models.CharField(choices=[('BUYER_DEBIT', 'Buyer Debit Reversal'), ('SELLER_SHARE_RELEASE', 'Seller Share Release'), ('FULL_REVERSAL', 'Full Reversal')], help_text='Type of reversal.', max_length=30)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount being reversed (if applicable).', max_digits=15, null=True)),
                ('external_ref', models.CharField(blank=True, default='', help_text='External reference for the reversal transaction.', max_length=128)),
                ('initiated_by', models.CharField(default='system', help_text='What initiated this reversal.', max_length=100)),
                ('initiated_at', models.DateTimeField(auto_now_add=True, help_text='When the reversal was initiated.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the reversal was completed.', null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INITIATED', help_text='Current reversal status.', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about the reversal.')),
                ('settlement', models.ForeignKey(help_text='The settlement being reversed.', on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='transactions.settlementintent')),
            ],
            options={
                'verbose_name': 'Settlement Reversal',
                'verbose_name_plural': 'Settlement Reversals',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='settlementintent',
            index=models.Index(fields=['state', 'updated_at'], name='transaction_state_212001_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementintent',
            index=models.Index(fields=['buyer', 'state'], name='transaction_buyer_i_bfa06c_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementintent',
            index=models.Index(fields=['seller', 'state'], name='transaction_seller__8e82ff_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementintent',
            index=models.Index(fields=['idempotency_key'], name='transaction_idempot_dea993_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementintent',
            index=models.Index(fields=['expires_at'], name='transaction_expires_911d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementevent',
            index=models.Index(fields=['intent', 'timestamp'], name='transaction_intent__7aca29_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementevent',
            index=models.Index(fields=['trigger'], name='transaction_trigger_acb280_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['buyer', 'recorded_at'], name='transaction_buyer_i_02dafb_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['seller', 'recorded_at'], name='transaction_seller__2f8945_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['sacco_id'], name='transaction_sacco_i_79b04d_idx'),
        ),
    ]
