# Generated by Django 5.0.7 on 2026-06-15 08:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('reason', models.CharField(choices=[('FUNDS_DEBITED_NO_SHARES', 'Funds debited but shares not received'), ('SHARES_RELEASED_NO_FUNDS', 'Shares released but funds not credited'), ('WRONG_AMOUNT', 'Wrong amount deducted'), ('UNAUTHORIZED', 'Unauthorized transaction'), ('SETTLEMENT_STUCK', 'Settlement taking too long'), ('OTHER', 'Other')], help_text='Reason for the dispute.', max_length=30)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the issue.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED_BUYER', 'Resolved - Buyer'), ('RESOLVED_SELLER', 'Resolved - Seller'), ('REJECTED', 'Rejected')], db_index=True, default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Admin notes on resolution.')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='transactions.settlementintent')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['status', 'opened_at'], name='transaction_status_76ec39_idx'), models.Index(fields=['raised_by', 'status'], name='transaction_raised__28c1c6_idx')],
                'unique_together': {('settlement', 'raised_by')},
            },
        ),
    ]
