# Generated by Django 5.0.7 on 2026-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='evidence',
            field=models.ImageField(blank=True, help_text='Screenshot or document supporting the dispute.', null=True, upload_to='disputes/%Y/%m/'),
        ),
    ]
