# Generated by Django 5.0.7 on 2026-06-13 10:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Webhook endpoint URL.', max_length=500)),
                ('secret', models.CharField(default=uuid.uuid4, help_text='Secret key for HMAC signature verification.', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('events', models.JSONField(default=list, help_text='List of WebhookEventType values to subscribe to.')),
                ('retry_limit', models.PositiveIntegerField(default=3)),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Subscription',
                'verbose_name_plural': 'Webhook Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SETTLEMENT_COMPLETED', 'Settlement Completed'), ('SETTLEMENT_DISPUTED', 'Settlement Disputed'), ('LIQUIDITY_REQUEST_CREATED', 'Liquidity Request Created'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_DISBURSED', 'Loan Disbursed'), ('CONTRIBUTION_RECEIVED', 'Contribution Received'), ('CHAMA_CREATED', 'Chama Created'), ('MEMBER_JOINED', 'Member Joined'), ('MEMBER_LEFT', 'Member Left')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhooksubscription')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
