# Generated by Django 5.0.7 on 2026-06-03 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number.', regex='^(?:\\+?254|0)?[17]\\d{8}$')]),
        ),
    ]
