# Generated by Django 5.0.7 on 2026-06-03 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number.', regex='^(?:\\+?254|0)?[17]\\d{8}$')]),
        ),
    ]
