# Generated by Django 5.0.7 on 2026-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Administrator'), ('SACCO_ADMIN', 'SACCO Administrator'), ('INVESTOR', 'Investor'), ('SELLER', 'Seller'), ('INSTITUTIONAL_BUYER', 'Institutional Buyer'), ('SUPPORT_AGENT', 'Support Agent')], max_length=30),
        ),
    ]
