# Generated by Django 5.0.7 on 2026-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(default=list, help_text='Hashed backup codes for 2FA recovery.'),
        ),
    ]
