# Generated by Django 5.0.7 on 2026-06-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_backup_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_last_verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_last_verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
