# Generated by Django 5.0.7 on 2026-06-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_last_verification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_transaction_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Maximum daily transaction amount.', max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_transaction_limit',
            field=models.DecimalField(decimal_places=2, default=200000.0, help_text='Maximum monthly transaction amount.', max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='per_transaction_limit',
            field=models.DecimalField(decimal_places=2, default=25000.0, help_text='Maximum single transaction amount.', max_digits=15),
        ),
    ]
