# Generated by Django 5.0.7 on 2026-06-15 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_daily_transaction_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public session identifier.'),
        ),
    ]
