# Generated by Django 5.0.7 on 2026-06-15 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_loginhistory_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public session identifier.', unique=True),
        ),
    ]
