# Generated by Django 5.0.7 on 2026-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_loginhistory_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token_used',
            field=models.BooleanField(default=False, help_text='Whether the current password reset token has been used.'),
        ),
    ]
