# Generated by Django 5.0.7 on 2026-06-16 18:15

import apps.core.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_password_reset_token_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=apps.core.fields.EncryptedCharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=apps.core.fields.EncryptedCharField(blank=True, db_index=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number.', regex='^(?:\\+?254|0)?[17]\\d{8}$')]),
        ),
    ]
