# Generated by Django 5.0.7 on 2026-06-17 21:14

import apps.core.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_national_id_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=apps.core.fields.EncryptedCharField(blank=True, db_index=True, max_length=500, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number.', regex='^(?:\\+?254|0)?[17]\\d{8}$')]),
        ),
    ]
