# Generated by Django 5.0.7 on 2026-07-07 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID_FRONT', 'National ID (Front)'), ('NATIONAL_ID_BACK', 'National ID (Back)'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('SELFIE', 'Selfie Photo'), ('UTILITY_BILL', 'Utility Bill (Proof of Address)')], max_length=30)),
                ('file', models.FileField(upload_to='kyc_documents/%Y/%m/%d/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'document_type'], name='users_kycdo_user_id_05a897_idx'), models.Index(fields=['is_verified'], name='users_kycdo_is_veri_5767ec_idx')],
            },
        ),
    ]
