import uuid
from decimal import Decimal
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.core.models import BaseModel


class ReceiptType(models.TextChoices):
    """Types of receipts generated by the platform."""

    SETTLEMENT_BUY = 'SETTLEMENT_BUY', _('Share Purchase')
    SETTLEMENT_SELL = 'SETTLEMENT_SELL', _('Share Sale')
    CHAMA_CONTRIBUTION = 'CHAMA_CONTRIBUTION', _('Chama Contribution')
    LOAN_REPAYMENT = 'LOAN_REPAYMENT', _('Loan Repayment')
    LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT', _('Loan Disbursement')
    PLATFORM_FEE = 'PLATFORM_FEE', _('Platform Fee')


class Receipt(BaseModel):

    receipt_number = models.CharField(
        max_length=50,
        unique=True,
        db_index=True,
        help_text=_("Unique receipt number (format: RCP-YYYYMMDD-XXXXXX).")
    )

    receipt_type = models.CharField(
        max_length=30,
        choices=ReceiptType.choices,
        help_text=_("Type of receipt.")
    )

    user = models.ForeignKey(
        'users.User',
        on_delete=models.PROTECT,
        related_name='receipts',
        help_text=_("The user this receipt belongs to.")
    )

    # Reference to the source transaction
    settlement = models.ForeignKey(
        'transactions.SettlementIntent',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='receipts',
        help_text=_("Related settlement if applicable.")
    )

    contribution = models.ForeignKey(
        'chamas.Contribution',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='receipts',
        help_text=_("Related contribution if applicable.")
    )

    loan_repayment = models.ForeignKey(
        'chamas.LoanRepayment',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='receipts',
        help_text=_("Related loan repayment if applicable.")
    )

    # Receipt details
    amount = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        help_text=_("Transaction amount in KSh.")
    )

    description = models.CharField(
        max_length=500,
        help_text=_("Human-readable description of the transaction.")
    )

    # Parties
    party_name = models.CharField(
        max_length=255,
        help_text=_("Name of the other party (buyer/seller/chama).")
    )

    # QR code for verification
    verification_code = models.CharField(
        max_length=64,
        unique=True,
        help_text=_("Unique verification code encoded in QR.")
    )

    # Generated PDF
    pdf_file = models.FileField(
        upload_to='receipts/%Y/%m/',
        null=True,
        blank=True,
        help_text=_("Generated PDF receipt file.")
    )

    generated_at = models.DateTimeField(
        auto_now_add=True,
        help_text=_("When the receipt was generated.")
    )

    class Meta:
        verbose_name = _('Receipt')
        verbose_name_plural = _('Receipts')
        ordering = ['-generated_at']
        indexes = [
            models.Index(fields=['user', 'receipt_type']),
            models.Index(fields=['receipt_number']),
            models.Index(fields=['generated_at']),
        ]

    def __str__(self):
        return f"Receipt {self.receipt_number} - {self.get_receipt_type_display()}"