# Generated by Django 5.0.7 on 2026-06-02 09:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Platform-generated unique transaction ID.', unique=True)),
                ('merchant_request_id', models.CharField(blank=True, default='', help_text='Merchant Request ID from M-Pesa API.', max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', help_text='Checkout Request ID from M-Pesa STK Push.', max_length=100)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, default='', help_text='M-Pesa receipt number for completed transaction.', max_length=50)),
                ('transaction_type', models.CharField(choices=[('CHAMA_CONTRIBUTION', 'Chama Contribution'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('SHARE_PURCHASE', 'SACCO Share Purchase'), ('PAYOUT', 'Chama Payout'), ('PLATFORM_FEE', 'Platform Fee')], default='CHAMA_CONTRIBUTION', help_text='Type of transaction.', max_length=30)),
                ('phone_number', models.CharField(help_text='Phone number sending the payment (format: 2547XXXXXXXX).', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in KSh.', max_digits=15, validators=[apps.core.validators.validate_positive_amount])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'STK Push Initiated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled by User'), ('TIMEOUT', 'Request Timed Out')], db_index=True, default='PENDING', help_text='Current transaction status.', max_length=20)),
                ('account_reference', models.CharField(blank=True, default='', help_text='Account reference sent to M-Pesa.', max_length=50)),
                ('transaction_description', models.CharField(blank=True, default='', help_text='Description of the transaction.', max_length=255)),
                ('initiated_at', models.DateTimeField(blank=True, help_text='When STK Push was sent to the user.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the transaction was confirmed via callback.', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When the transaction failed or timed out.', null=True)),
                ('stk_request_data', models.JSONField(default=dict, help_text='Request payload sent to M-Pesa STK Push API.')),
                ('stk_response_data', models.JSONField(default=dict, help_text='Response from M-Pesa STK Push API.')),
                ('callback_data', models.JSONField(default=dict, help_text='Raw callback data received from M-Pesa.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if transaction failed.')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts for failed callbacks.')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether this transaction has been reconciled with chama records.')),
                ('chama', models.ForeignKey(blank=True, help_text='The chama this payment is for (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='chamas.chama')),
                ('contribution', models.ForeignKey(blank=True, help_text='The contribution this payment fulfills.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='chamas.contribution')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user making the payment.', on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='mpesa_mpesa_user_id_fbd830_idx'), models.Index(fields=['checkout_request_id'], name='mpesa_mpesa_checkou_ad0fa5_idx'), models.Index(fields=['mpesa_receipt_number'], name='mpesa_mpesa_mpesa_r_63a7c8_idx'), models.Index(fields=['status', 'created_at'], name='mpesa_mpesa_status_b49ae6_idx')],
            },
        ),
    ]
