# Generated by Django 5.0.7 on 2026-09-20 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0006_chama_constitution_chama_constitution_uploaded_at_and_more'),
        ('mpesa', '0001_initial'),
        ('transactions', '0003_dispute_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='settlement',
            field=models.ForeignKey(blank=True, help_text='The settlement intent this payment fulfills.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='transactions.settlementintent'),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt_number', ''), _negated=True), fields=('mpesa_receipt_number',), name='unique_non_empty_mpesa_receipt_number'),
        ),
    ]
