# Generated by Django 5.0.7 on 2026-06-13 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['chama', 'period_start', 'status'], name='chamas_cont_chama_i_df26cf_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['chama', 'borrower', 'status'], name='chamas_loan_chama_i_5f77b2_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='chamas_loan_due_dat_c1851a_idx'),
        ),
    ]
