# Generated by Django 5.0.7 on 2026-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0002_contribution_chamas_cont_chama_i_df26cf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='health_score',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Overall chama health score (0.0-100.0).', max_digits=4),
        ),
        migrations.AddField(
            model_name='chama',
            name='health_score_breakdown',
            field=models.JSONField(default=dict, help_text='Breakdown of score components.'),
        ),
        migrations.AddField(
            model_name='chama',
            name='health_score_grade',
            field=models.CharField(blank=True, default='', help_text='Letter grade (A+, A, B, C, D, F).', max_length=3),
        ),
        migrations.AddField(
            model_name='chama',
            name='health_score_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the health score was last calculated.', null=True),
        ),
    ]
