# Generated by Django 5.0.7 on 2026-06-13 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0003_chama_health_score_chama_health_score_breakdown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='early_repayment_discount',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Discount percentage for early full repayment.', max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_restructured',
            field=models.BooleanField(default=False, help_text='Whether this loan has been restructured.'),
        ),
        migrations.AddField(
            model_name='loan',
            name='original_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Original duration before restructuring.', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='original_monthly_installment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original installment before restructuring.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='restructuring_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for loan restructuring.'),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('voting_method', models.CharField(choices=[('MAJORITY', 'Simple Majority'), ('TWO_THIRDS', 'Two-Thirds Majority'), ('UNANIMOUS', 'Unanimous')], default='MAJORITY', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether votes are anonymous.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='chamas.chama')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to='chamas.chamamember')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='chamas.poll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chamas.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_votes', to='chamas.poll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='chamas.chamamember')),
            ],
            options={
                'unique_together': {('poll', 'voter')},
            },
        ),
    ]
