# Generated by Django 5.0.7 on 2026-06-16 10:04

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0004_loan_early_repayment_discount_loan_is_restructured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='default_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for default.'),
        ),
        migrations.AddField(
            model_name='loan',
            name='defaulted_at',
            field=models.DateTimeField(blank=True, help_text='When the loan was marked as defaulted.', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='recovery_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount recovered from member contributions.', max_digits=15),
        ),
    ]
