# Generated by Django 5.0.7 on 2026-06-16 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0005_loan_default_reason_loan_defaulted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chama',
            name='constitution',
            field=models.FileField(blank=True, help_text='Chama constitution document.', null=True, upload_to='chama_constitutions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='chama',
            name='constitution_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the constitution was uploaded.', null=True),
        ),
        migrations.AddField(
            model_name='chama',
            name='constitution_version',
            field=models.CharField(blank=True, default='1.0', help_text='Version of the uploaded constitution.', max_length=20),
        ),
        migrations.CreateModel(
            name='ConstitutionAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constitution_agreements', to='chamas.chama')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constitution_agreements', to='chamas.chamamember')),
            ],
            options={
                'verbose_name': 'Constitution Agreement',
                'verbose_name_plural': 'Constitution Agreements',
                'ordering': ['-agreed_at'],
                'unique_together': {('member', 'version')},
            },
        ),
    ]
