# Generated by Django 5.0.7 on 2026-06-13 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('report_type', models.CharField(choices=[('TRANSACTION_HISTORY', 'Transaction History'), ('CONTRIBUTION_REPORT', 'Contribution Report'), ('LOAN_STATEMENT', 'Loan Statement'), ('MEMBER_LIST', 'Member List'), ('CHAMA_FINANCIAL', 'Chama Financial Summary'), ('DIVIDEND_STATEMENT', 'Dividend Statement'), ('TAX_STATEMENT', 'Tax Statement')], help_text='Type of report requested.', max_length=30)),
                ('report_format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF'), ('EXCEL', 'Excel')], default='CSV', help_text='Output format.', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Current generation status.', max_length=20)),
                ('title', models.CharField(help_text='Human-readable report title.', max_length=255)),
                ('filters', models.JSONField(default=dict, help_text='Filters applied (date range, chama_id, etc.).')),
                ('report_file', models.FileField(blank=True, help_text='Generated report file.', null=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('record_count', models.PositiveIntegerField(blank=True, help_text='Number of records in the report.', null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True, help_text='When the request was queued.')),
                ('started_at', models.DateTimeField(blank=True, help_text='When generation started.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When generation completed.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the download link expires.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if generation failed.')),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task ID for this report.', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who requested the report.', on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Request',
                'verbose_name_plural': 'Report Requests',
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='reports_rep_user_id_cb8f34_idx'), models.Index(fields=['status', 'queued_at'], name='reports_rep_status_d2c9c4_idx')],
            },
        ),
    ]
