from decimal import Decimal

# LOAN DEFAULTS
LOAN_DEFAULT_GRACE_PERIOD_DAYS = 30
LOAN_DEFAULT_AUTO_DETECTION_ENABLED = True

# TRANSACTION THRESHOLDS
LARGE_TRANSACTION_THRESHOLD = Decimal('100000.00')
SETTLEMENT_COOLING_PERIOD_SECONDS = 1800  # 30 minutes

# FILE UPLOAD LIMITS
MAX_UPLOAD_SIZE_PROFILE_PICTURE = 5 * 1024 * 1024   # 5MB
MAX_UPLOAD_SIZE_SACCO_LOGO = 2 * 1024 * 1024         # 2MB
MAX_UPLOAD_SIZE_EVIDENCE = 10 * 1024 * 1024           # 10MB
MAX_UPLOAD_SIZE_CONSTITUTION = 10 * 1024 * 1024       # 10MB

# OTP & VERIFICATION
OTP_EXPIRY_HOURS = 24
OTP_RATE_LIMIT_SECONDS = 60
OTP_MAX_ATTEMPTS = 5
OTP_LENGTH = 6

# CHAMA LIMITS
MAX_BULK_CONTRIBUTIONS = 100
MAX_BULK_INVITES = 200
MAX_CHAMA_MEMBERS_DEFAULT = 100

# RATE LIMITING
AUTH_RATE_LIMIT = '5/minute'
AUTH_ANON_RATE_LIMIT = '3/minute'
MUTATION_RATE_LIMIT = '20/minute'
READ_RATE_LIMIT = '100/minute'
SENSITIVE_RATE_LIMIT = '3/minute'
BULK_RATE_LIMIT = '5/minute'
REPORT_RATE_LIMIT = '5/hour'

# CACHE TTLs
PLATFORM_DASHBOARD_CACHE_TTL = 300   # 5 minutes
USER_DASHBOARD_CACHE_TTL = 120       # 2 minutes
MPESA_TOKEN_CACHE_TTL = 3500         # 58 minutes

# CREDIT SCORING
CREDIT_SCORE_MAX = 850
CREDIT_SCORE_MIN = 300
CREDIT_SCORE_GRADE_THRESHOLDS = {
    'A+': 800, 'A': 750, 'B': 700, 'C': 600, 'D': 500, 'E': 0,
}

# IDEMPOTENCY
IDEMPOTENCY_KEY_TTL = 86400  # 24 hours

# DISPUTE
DISPUTE_COOLING_PERIOD_SECONDS = 1800  # 30 minutes

# ACCOUNT DELETION
ACCOUNT_DELETION_GRACE_PERIOD_DAYS = 30

# POLLING/VOTING
POLL_MAJORITY_THRESHOLD = 50.0       # percentage
POLL_TWO_THIRDS_THRESHOLD = 66.7     # percentage
POLL_UNANIMOUS_THRESHOLD = 100.0     # percentage