# Generated by Django 5.0.7 on 2026-06-02 09:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique template identifier.', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('CHAMA_CONTRIBUTION', 'Chama Contribution'), ('CHAMA_LOAN', 'Chama Loan'), ('CHAMA_MEETING', 'Chama Meeting'), ('CHAMA_MEMBER', 'Chama Member'), ('INVESTMENT_OPPORTUNITY', 'Investment Opportunity'), ('INVESTMENT_OFFER', 'Investment Offer'), ('INVESTMENT_CONNECTION', 'Investment Connection'), ('SETTLEMENT', 'Settlement'), ('DISPUTE', 'Dispute'), ('SYSTEM', 'System'), ('SECURITY', 'Security'), ('MARKETING', 'Marketing')], help_text='Category this template belongs to.', max_length=50)),
                ('title_template', models.CharField(help_text='Template for notification title. Use {variable} placeholders.', max_length=255)),
                ('body_template', models.TextField(help_text='Template for notification body. Use {variable} placeholders.')),
                ('sms_template', models.TextField(blank=True, default='', help_text='Short SMS version of the template (160 chars max).')),
                ('email_subject_template', models.CharField(blank=True, default='', help_text='Email subject line template.', max_length=255)),
                ('email_body_template', models.TextField(blank=True, default='', help_text='HTML email body template.')),
                ('default_channels', models.JSONField(default=list, help_text='Default delivery channels for this template.')),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Default priority level.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last modified.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the record.', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. When True, the record is considered deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted.', null=True)),
                ('category', models.CharField(choices=[('CHAMA_CONTRIBUTION', 'Chama Contribution'), ('CHAMA_LOAN', 'Chama Loan'), ('CHAMA_MEETING', 'Chama Meeting'), ('CHAMA_MEMBER', 'Chama Member'), ('INVESTMENT_OPPORTUNITY', 'Investment Opportunity'), ('INVESTMENT_OFFER', 'Investment Offer'), ('INVESTMENT_CONNECTION', 'Investment Connection'), ('SETTLEMENT', 'Settlement'), ('DISPUTE', 'Dispute'), ('SYSTEM', 'System'), ('SECURITY', 'Security'), ('MARKETING', 'Marketing')], help_text='Notification category.', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level.', max_length=10)),
                ('title', models.CharField(help_text='Notification title.', max_length=255)),
                ('body', models.TextField(help_text='Notification body text.')),
                ('action_url', models.CharField(blank=True, default='', help_text='Deep link or URL for notification action.', max_length=500)),
                ('action_text', models.CharField(blank=True, default='', help_text='Text for the action button.', max_length=100)),
                ('image_url', models.URLField(blank=True, default='', help_text='Optional image URL for rich notifications.')),
                ('data', models.JSONField(default=dict, help_text='Additional structured data for the notification.')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read.')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read.', null=True)),
                ('channels_sent', models.JSONField(default=list, help_text='Channels this notification was sent to.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who performed the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The recipient user.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used to generate this notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('EMAIL', 'Email')], help_text='Delivery channel.', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', help_text='Current delivery status.', max_length=20)),
                ('recipient', models.CharField(help_text='Recipient address (email, phone, or device token).', max_length=255)),
                ('provider_message_id', models.CharField(blank=True, default='', help_text='Message ID from the delivery provider.', max_length=255)),
                ('provider_response', models.JSONField(default=dict, help_text='Raw response from the delivery provider.')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was sent.', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When delivery was confirmed.', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if delivery failed.')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of delivery retries.')),
                ('notification', models.ForeignKey(help_text='The notification being delivered.', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Delivery',
                'verbose_name_plural': 'Notification Deliveries',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_token', models.CharField(help_text='Firebase Cloud Messaging registration token.', max_length=500, unique=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], help_text='Type of device.', max_length=20)),
                ('device_name', models.CharField(blank=True, default='', help_text='Human-readable device name.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this device is currently active.')),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this device was active.')),
                ('app_version', models.CharField(blank=True, default='', help_text='App version installed on the device.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who owns this device.', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHAMA_CONTRIBUTION', 'Chama Contribution'), ('CHAMA_LOAN', 'Chama Loan'), ('CHAMA_MEETING', 'Chama Meeting'), ('CHAMA_MEMBER', 'Chama Member'), ('INVESTMENT_OPPORTUNITY', 'Investment Opportunity'), ('INVESTMENT_OFFER', 'Investment Offer'), ('INVESTMENT_CONNECTION', 'Investment Connection'), ('SETTLEMENT', 'Settlement'), ('DISPUTE', 'Dispute'), ('SYSTEM', 'System'), ('SECURITY', 'Security'), ('MARKETING', 'Marketing')], help_text='Notification category.', max_length=50)),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Receive in-app notifications for this category.')),
                ('push_enabled', models.BooleanField(default=True, help_text='Receive push notifications for this category.')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Receive SMS notifications for this category.')),
                ('email_enabled', models.BooleanField(default=False, help_text='Receive email notifications for this category.')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no push notifications).', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours.', null=True)),
                ('user', models.ForeignKey(help_text='The user.', on_delete=django.db.models.deletion.CASCADE, related_name='notif_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'category'], name='notificatio_user_id_4652f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
    ]
