# Generated by Django 5.0.7 on 2026-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique key to prevent duplicate delivery attempts.', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='unique_notification_channel_delivery'),
        ),
    ]
