# Generated by Django 5.0.7 on 2026-06-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdelivery_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='sw_body_template',
            field=models.TextField(blank=True, default='', help_text='Swahili body template.'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='sw_sms_template',
            field=models.TextField(blank=True, default='', help_text='Swahili SMS template (160 chars max).'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='sw_title_template',
            field=models.CharField(blank=True, default='', help_text='Swahili title template.', max_length=255),
        ),
    ]
