# Generated by Django 5.0.7 on 2026-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationtemplate_sw_body_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('CHAMA_CONTRIBUTION', 'Chama Contribution'), ('CHAMA_LOAN', 'Chama Loan'), ('CHAMA_MEETING', 'Chama Meeting'), ('CHAMA_MEMBER', 'Chama Member'), ('INVESTMENT_OPPORTUNITY', 'Investment Opportunity'), ('INVESTMENT_OFFER', 'Investment Offer'), ('INVESTMENT_CONNECTION', 'Investment Connection'), ('SETTLEMENT', 'Settlement'), ('SETTLEMENT_STATUS', 'Settlement Status Update'), ('DISPUTE', 'Dispute'), ('SYSTEM', 'System'), ('SECURITY', 'Security'), ('MARKETING', 'Marketing')], help_text='Notification category.', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='category',
            field=models.CharField(choices=[('CHAMA_CONTRIBUTION', 'Chama Contribution'), ('CHAMA_LOAN', 'Chama Loan'), ('CHAMA_MEETING', 'Chama Meeting'), ('CHAMA_MEMBER', 'Chama Member'), ('INVESTMENT_OPPORTUNITY', 'Investment Opportunity'), ('INVESTMENT_OFFER', 'Investment Offer'), ('INVESTMENT_CONNECTION', 'Investment Connection'), ('SETTLEMENT', 'Settlement'), ('SETTLEMENT_STATUS', 'Settlement Status Update'), ('DISPUTE', 'Dispute'), ('SYSTEM', 'System'), ('SECURITY', 'Security'), ('MARKETING', 'Marketing')], help_text='Notification category.', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='category',
            field=models.CharField(choices=[('CHAMA_CONTRIBUTION', 'Chama Contribution'), ('CHAMA_LOAN', 'Chama Loan'), ('CHAMA_MEETING', 'Chama Meeting'), ('CHAMA_MEMBER', 'Chama Member'), ('INVESTMENT_OPPORTUNITY', 'Investment Opportunity'), ('INVESTMENT_OFFER', 'Investment Offer'), ('INVESTMENT_CONNECTION', 'Investment Connection'), ('SETTLEMENT', 'Settlement'), ('SETTLEMENT_STATUS', 'Settlement Status Update'), ('DISPUTE', 'Dispute'), ('SYSTEM', 'System'), ('SECURITY', 'Security'), ('MARKETING', 'Marketing')], help_text='Category this template belongs to.', max_length=50),
        ),
    ]
